package com.smartapps.saveyourreferrals.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table APP_INFO.
 */
public class AppInfo {

    private String app_name;
    private String package_name_name;
    private String referral_text;
    private String is_favourite;
    private String base64_applogo;
    private String test1;
    private String test2;
    private String test3;
    private String test4;
    private String time;

    public AppInfo() {
    }

    public AppInfo(String package_name_name) {
        this.package_name_name = package_name_name;
    }

    public AppInfo(String app_name, String package_name_name, String referral_text, String is_favourite, String base64_applogo, String test1, String test2, String test3, String test4, String time) {
        this.app_name = app_name;
        this.package_name_name = package_name_name;
        this.referral_text = referral_text;
        this.is_favourite = is_favourite;
        this.base64_applogo = base64_applogo;
        this.test1 = test1;
        this.test2 = test2;
        this.test3 = test3;
        this.test4 = test4;
        this.time = time;
    }

    public String getApp_name() {
        return app_name;
    }

    public void setApp_name(String app_name) {
        this.app_name = app_name;
    }

    public String getPackage_name_name() {
        return package_name_name;
    }

    public void setPackage_name_name(String package_name_name) {
        this.package_name_name = package_name_name;
    }

    public String getReferral_text() {
        return referral_text;
    }

    public void setReferral_text(String referral_text) {
        this.referral_text = referral_text;
    }

    public String getIs_favourite() {
        return is_favourite;
    }

    public void setIs_favourite(String is_favourite) {
        this.is_favourite = is_favourite;
    }

    public String getBase64_applogo() {
        return base64_applogo;
    }

    public void setBase64_applogo(String base64_applogo) {
        this.base64_applogo = base64_applogo;
    }

    public String getTest1() {
        return test1;
    }

    public void setTest1(String test1) {
        this.test1 = test1;
    }

    public String getTest2() {
        return test2;
    }

    public void setTest2(String test2) {
        this.test2 = test2;
    }

    public String getTest3() {
        return test3;
    }

    public void setTest3(String test3) {
        this.test3 = test3;
    }

    public String getTest4() {
        return test4;
    }

    public void setTest4(String test4) {
        this.test4 = test4;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

}
